name: Deploy Lambda Functions

on:
  push:
    branches: [main]
    paths:
      - 'modules/lambda/lambda/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1  # Thay đổi theo region của bạn
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # ARN của IAM role được tạo bởi module CI/CD
        role-session-name: GitHubActions-Lambda-Deploy
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies for stream processor
      run: |
        mkdir -p /tmp/stream_processor
        cp modules/lambda/lambda/stream_processor.py /tmp/stream_processor/
        cd /tmp/stream_processor
        # Tạo requirements.txt nếu cần
        if [ -f ../../modules/lambda/lambda/requirements.txt ]; then
          pip install -r ../../modules/lambda/lambda/requirements.txt -t .
        fi
    
    - name: Install dependencies for query handler  
      run: |
        mkdir -p /tmp/query_handler
        cp modules/lambda/lambda/query_handler.py /tmp/query_handler/
        cd /tmp/query_handler
        # Tạo requirements.txt nếu cần
        if [ -f ../../modules/lambda/lambda/requirements.txt ]; then
          pip install -r ../../modules/lambda/lambda/requirements.txt -t .
        fi
    
    - name: Package Lambda functions
      run: |
        # Package stream processor
        cd /tmp/stream_processor
        zip -r /tmp/stream_processor.zip . -x "*.pyc" "__pycache__/*"
        
        # Package query handler
        cd /tmp/query_handler  
        zip -r /tmp/query_handler.zip . -x "*.pyc" "__pycache__/*"
    
    - name: Deploy Stream Processor Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ vars.PROJECT_NAME }}-stream-processor-${{ vars.ENVIRONMENT }} \
          --zip-file fileb:///tmp/stream_processor.zip
        
        echo "Stream processor deployed successfully!"
    
    - name: Deploy Query Handler Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ vars.PROJECT_NAME }}-query-handler-${{ vars.ENVIRONMENT }} \
          --zip-file fileb:///tmp/query_handler.zip
          
        echo "Query handler deployed successfully!"
    
    - name: Wait for deployment completion
      run: |
        # Chờ function update hoàn thành
        aws lambda wait function-updated \
          --function-name ${{ vars.PROJECT_NAME }}-stream-processor-${{ vars.ENVIRONMENT }}
        
        aws lambda wait function-updated \
          --function-name ${{ vars.PROJECT_NAME }}-query-handler-${{ vars.ENVIRONMENT }}
        
        echo "All Lambda functions deployed and ready!"
    
    - name: Test Lambda functions (optional)
      run: |
        # Test stream processor
        echo "Testing stream processor..."
        aws lambda invoke \
          --function-name ${{ vars.PROJECT_NAME }}-stream-processor-${{ vars.ENVIRONMENT }} \
          --payload '{"test": true}' \
          /tmp/stream_response.json
        
        # Test query handler
        echo "Testing query handler..."
        aws lambda invoke \
          --function-name ${{ vars.PROJECT_NAME }}-query-handler-${{ vars.ENVIRONMENT }} \
          --payload '{"test": true}' \
          /tmp/query_response.json
        
        echo "Lambda function tests completed!"